config/routes.rb
Rails.application.routes.draw do
  resources :xpenses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/xpense.rb
class Xpense < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/xpenses_controller.rb
class XpensesController < ApplicationController
  before_action :set_xpense, only: [:show, :edit, :update, :destroy]

  # GET /xpenses
  # GET /xpenses.json
  def index
    @xpenses = Xpense.all
  end

  # GET /xpenses/1
  # GET /xpenses/1.json
  def show
  end

  # GET /xpenses/new
  def new
    @xpense = Xpense.new
  end

  # GET /xpenses/1/edit
  def edit
  end

  # POST /xpenses
  # POST /xpenses.json
  def create
    @xpense = Xpense.new(xpense_params)

    respond_to do |format|
      if @xpense.save
        format.html { redirect_to @xpense, notice: 'Xpense was successfully created.' }
        format.json { render :show, status: :created, location: @xpense }
      else
        format.html { render :new }
        format.json { render json: @xpense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xpenses/1
  # PATCH/PUT /xpenses/1.json
  def update
    respond_to do |format|
      if @xpense.update(xpense_params)
        format.html { redirect_to @xpense, notice: 'Xpense was successfully updated.' }
        format.json { render :show, status: :ok, location: @xpense }
      else
        format.html { render :edit }
        format.json { render json: @xpense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xpenses/1
  # DELETE /xpenses/1.json
  def destroy
    @xpense.destroy
    respond_to do |format|
      format.html { redirect_to xpenses_url, notice: 'Xpense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xpense
      @xpense = Xpense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xpense_params
      params.require(:xpense).permit(:name, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/xpenses_helper.rb
module XpensesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/xpenses/_form.html.erb
<%= form_for(xpense) do |f| %>
  <% if xpense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xpense.errors.count, "error") %> prohibited this xpense from being saved:</h2>

      <ul>
      <% xpense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xpenses/edit.html.erb
<h1>Editing Xpense</h1>

<%= render 'form', xpense: @xpense %>

<%= link_to 'Show', @xpense %> |
<%= link_to 'Back', xpenses_path %>

app/views/xpenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Xpenses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xpenses.each do |xpense| %>
      <tr>
        <td><%= xpense.name %></td>
        <td><%= xpense.amount %></td>
        <td><%= link_to 'Show', xpense %></td>
        <td><%= link_to 'Edit', edit_xpense_path(xpense) %></td>
        <td><%= link_to 'Destroy', xpense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xpense', new_xpense_path %>

app/views/xpenses/new.html.erb
<h1>New Xpense</h1>

<%= render 'form', xpense: @xpense %>

<%= link_to 'Back', xpenses_path %>

app/views/xpenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @xpense.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @xpense.amount %>
</p>

<%= link_to 'Edit', edit_xpense_path(@xpense) %> |
<%= link_to 'Back', xpenses_path %>